version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test: # This is the name of the job, feel free to change it to better match what you're trying to do!
   docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: upgrade pip
          command: '/home/circleci/.pyenv/versions/3.8.12/bin/python3.8 -m pip install --upgrade pip'
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: conda-requirements.txt
      - run:
          name: Run tests
          command: pytest

orkflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
